- hosts: local
  user: cloud
  become: true

  vars:
    cozycloud:
      floating_ip: "{{ lookup('file', '/etc/stack_floating_ip') }}"

  tasks:
    - name: Debconf cozy #fichier de reponse#
      debconf:
        name="{{ item.name }}"
        question="{{ item.question }}"
        value="{{ item.value }}"
        vtype="{{ item.vtype }}"
      with_items:
        - { name: 'cozy', question: 'cozy/nodejs_minimum', vtype: "boolean", value: true }
        - { name: 'cozy', question: 'cozy/fqdn', vtype: "string", value: "{{ cozycloud.floating_ip }}" }
        - { name: 'cozy', question: 'cozy/purge_db', vtype: "boolean", value: true}
        - { name: 'cozy', question: 'cozy/certificate', vtype: "note", value: "" }
        - { name: 'cozy', question: 'cozy/nodejs_maximum', vtype: "boolean", value: true}
        - { name: 'postfix', question: 'postfix/main_mailer_type', vtype: 'select', value: 'Local only'}
        - { name: 'postfix', question: 'postfix/mailname', vtype: 'string', value: "{{ ansible_fqdn }}"}

    - name: Reconfigure Cozy
      shell:
        dpkg-reconfigure -u -f noninteractive cozy

    - name: Generate Certificat
      shell:
        "openssl req -x509 -nodes -newkey rsa:4096 -keyout /etc/cozy/server.key -out /etc/cozy/server.crt -days 3650 -subj \"/CN={{ cozycloud.floating_ip }}\" && touch /etc/cozy/.cw_post_install"
        creates="/etc/cozy/.cw_post_install"
      notify: restart nginx

    - name: Let's encrypt install
      shell:
        git clone https://github.com/letsencrypt/letsencrypt /root/letsencrypt
      notify: stop nginx

    - name: Backup CRT cozy
      shell:
        mv /etc/cozy/server.key /etc/cozy/server.key.backup
        mv /etc/cozy/server.crt /etc/cozy/server.crt.backup

    - name: Include Vars FQDN
      include_vars: /etc/ansible/cozy-vars.yml

    - name: Generate let's encrypt certificate
      shell: |
        /root/letsencrypt/letsencrypt-auto certonly
         --standalone --agree-tos
         --email cozy@cloudwatt.com -d {{ cozy_domain }}
         --standalone-supported-challenges tls-sni-01

    - name: Copy crt to cozy
      shell:
        ln -s /etc/letsencrypt/live/{{ cozy_domain }}/privkey.pem /etc/cozy/server.key
        ln -s /etc/letsencrypt/live/{{ cozy_domain }}/fullchain.pem /etc/cozy/server.crt
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name=nginx
        state=restarted

    - name: stop nginx
      service:
        name=nginx
        state=stop