- hosts: local
  user: cloud
  become: true

  vars:
    cozycloud:
      floating_ip: "{{ lookup('file', '/etc/stack_floating_ip') }}"

  tasks:
    - name: Debconf cozy #fichier de reponse#
      debconf:
        name="{{ item.name }}"
        question="{{ item.question }}"
        value="{{ item.value }}"
        vtype="{{ item.vtype }}"
      with_items:
        - { name: 'cozy', question: 'cozy/nodejs_minimum', vtype: "boolean", value: true }
        - { name: 'cozy', question: 'cozy/fqdn', vtype: "string", value: "{{ cozycloud.floating_ip }}" }
        - { name: 'cozy', question: 'cozy/purge_db', vtype: "boolean", value: true}
        - { name: 'cozy', question: 'cozy/certificate', vtype: "note", value: "" }
        - { name: 'cozy', question: 'cozy/nodejs_maximum', vtype: "boolean", value: true}
        - { name: 'postfix', question: 'postfix/main_mailer_type', vtype: 'select', value: 'Local only'}
        - { name: 'postfix', question: 'postfix/mailname', vtype: 'string', value: "{{ ansible_fqdn }}"}

    - name: Reconfigure Cozy
      shell:
        dpkg-reconfigure -u -f noninteractive cozy
