- hosts: local
  user: cloud
  sudo: true

  vars:
    cozycloud:
      floating_ip: "{{ lookup('file', '/etc/stack_floating_ip') }}"

  tasks:
    - name: Debconf cozy #fichier de reponse#
      debconf:
        name=cozy
        question={{ item.question }}
        value={{ item.value }}
        vtype={{ item.vtype }}

      with_items:
        - { question: "cozy/nodejs_minimum", vtype: "boolean", value: true }
        - { question: "cozy/fqdn", vtype: "text", value: "{{ cozycloud.floatting_ip }}" }
        - { question: "cozy/purge_db", vtype: "boolean", value: true}
        - { question: "cozy/certificate", vtype: "not", value: "" }
        - { question: "cozy/nodejs_maximum", vtype: "boolean", value: true}

    - name: install Cozy
       apt:
        pkg=cozy
        state=present
