---
- hosts: local
  become: yes

  tasks:
    - name: Création de la base de données icehrmdb
      mysql_db:
        name: icehrmdb
        state: present

    - name: Création de l'utilisateur icehrmuser
      mysql_user:
        name: icehrmuser
        password: "{{sqlpass}}"
        priv: "*.*:ALL"
        state: present