---
- hosts: local
  become: yes

  tasks:
    - name: Stopping MariaDB
      service:
        name: mysql
        state: stopped

    - name: Adding MariaDB conf
      shell: cp "/root/mariadb_{{instance_name}}.cnf" /etc/mysql/conf.d/mariadb.cnf

    - name: Format and mounting volume
      shell: chmod a+x /root/format && /root/format && mkdir /srv/icehrm && mount /dev/vdb /srv/icehrm && mkdir /srv/icehrm/data && mkdir /srv/icehrm/mysql

    - name: Copying MySQL files
      shell: cp -R /var/lib/mysql/* /srv/icehrm/mysql/

    - name: Removing old MySQL files
      file:
        path: /var/lib/mysql
        state: absent

    - name: Mounting MySQL folder
      mount:
        opts: bind
        fstype: none
        src: /srv/icehrm/mysql
        name: /var/lib/mysql
        state: mounted

    - name: Adding mounting at boot
      shell: echo "/dev/vdb   /srv/icehrm   ext4   defaults   0   0\n/srv/icehrm/mysql   /var/lib/mysql   none   bind   0   0" >> /etc/fstab

#    - name: Mounting volume
#      mount:
#        name: /srv/glusterfs
#        src: /dev/vdb
#        fstype: ext4
#        state: present