---
- name: Waiting for inst1 to continue
  wait_for:
     host: inst1
     port: 4567
     delay: 1
     timeout: 300

- name: Starting MariaDB
  service:
    name: mysql
    state: started

# - name: Adding GlusterFS Client mounting at boot
#   shell: echo "inst2:/gfscluster_icehrm   /var/www/html/app   glusterfs   defaults,_netdev   0   0" >> /etc/fstab