- hosts: local
  user: cloud
  sudo: true

  vars:
    wp_db_name: mediawiki


    mediawiki:
      sitename: "{{ lookup('file', '/etc/mediawiki/site_name') }}"
      floating_ip: "{{ lookup('file', '/etc/stack_floating_ip') }}"
      password_db: "{{ lookup('password', '/etc/mediawiki/password_db chars=ascii_letters,digits,hexdigits,punctuation') }}"
      secret_key: "{{ lookup('password', '/etc/mediawiki/secret_key length=65 chars=ascii_letters,digits') }}"
      upgrade_key: "{{ lookup('password', '/etc/mediawiki/secret_key length=17 chars=ascii_letters,digits') }}"


  tasks:
    - name: LocalSetting
      template:
        src=LocalSettings.php.j2
        dest=/etc/mediawiki/LocalSettings.php
        owner=root
        group=www-data
        mode=0600

        
    - name: mysql database is created
      mysql_db:
        name=mediawiki
        state=present

    - name: mysql user is created
      mysql_user:
        name=mediawiki
        password="{{ mediawiki.password_db }}"
        priv="wordpress.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER"
        state=present
