---
- hosts: local

  vars:
    bundle_label: "default_bundle_label"
    bundle_path: "default_bundle_path"
    bundle_src_img: "default_bundle_src_img"
    bundle_img_os: "default_bundle_img_os"
    vm_flavor: "16"
    bundle_img_name: "{{ bundle_label }}-{{ ansible_date_time.date }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
    packer_file: "bundle-ansible.packer.json"

  tasks:
    - name: building server image with Packer
      shell: "packer build -var 'bundle_path={{ bundle_path }}' -var 'source_image={{ bundle_src_img }}' -var 'image_name={{ bundle_img_name }}' -var 'factory_flavor={{ vm_flavor }}' {{ packer_file }} > packer.{{ bundle_img_name }}.log 2>&1"
      register: packer
      ignore_errors: yes

    - debug: msg="Packer failed, search packer.{{ bundle_img_name }}.log for debug hints."
      when: packer|failed

    - name: get built image id
      shell: openstack image list --private | grep {{ bundle_img_name }} | tr "|" " " | tr -s " " | cut -d " " -f2
      register: packed_image_id

    - debug: var=packed_image_id



