---
- hosts: local

  vars:
    bundle_label: "default_bundle_label"
    bundle_path: "default_bundle_path"
    bundle_src_img: "default_bundle_src_img"
    bundle_img_os: "default_bundle_img_os"
    vm_flavor: "16"
    bundle_img_name: "{{ bundle_label }}-{{ ansible_date_time.date }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
    packer_file: "bundle-ansible.packer.json"

  tasks:
    - name: building server image with Packer
      shell: "packer build -var 'bundle_path={{ bundle_path }}' -var 'source_image={{ bundle_src_img }}' -var 'image_name={{ bundle_img_name }}' -var 'factory_flavor={{ vm_flavor }}' {{ packer_file }} > packer.{{ bundle_img_name }}.log 2>&1"

    - name: retrieve built image id
      shell: openstack image list --private | grep {{ bundle_img_name }} | tr "|" " " | tr -s " " | cut -d " " -f2
      register: packed_image_id

    - name: building remove-property string for image cleanup
      shell: openstack image show -f value -c properties {{ packed_image_id.stdout }} | tr ", " "\n" | grep -v "^$" | cut -d"=" -f1 | grep -v -E "(cw_os|cw_origin|hw_rng_model)" | sed 's/^/--remove-property /g' | tr "\n" " "
      register: purge_props

    - name: removing useless properties from built image
      shell: glance image-update {{ purge_props.stdout }} {{ packed_image_id.stdout }}





