- hosts: local
  remote_user: cloud
  become: yes

  vars:
    os_image_factory:
      packer:
        version: "0.8.6"
        zip_url: "https://dl.bintray.com/mitchellh/packer/packer_{{ os_image_factory.packer.version }}_linux_amd64.zip"
      jenkins_url: "http://127.0.0.1:8080"


  tasks:
    - name: jenkins key server is known
      apt_key:
        url="http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key"
        state=present

    - name: jenkins apt server is known
      apt_repository:
        repo="deb http://pkg.jenkins-ci.org/debian binary/"
        state=present

    - name: packages installed
      apt:
        pkg="{{ item }}"
        state=present
        update_cache=yes
      with_items:
        - libguestfs-tools
        - libffi-dev
        - python-cffi
        - libssl-dev
        - jenkins
        - unzip
        - emacs
      register: result
      until: result|success
      retries: 10
      delay: 2

    - name: jenkins is kvm member
      user:
        name=jenkins
        groups=kvm
        append=yes

    - name: jenkins service is up
      service: name=jenkins state=restarted enabled=yes

    - name: common aliases
      copy:
        dest=/etc/profile.d/aliases.sh
        content="alias ll=\"ls -aul\""
        owner=root
        group=root
        mode=0644

    - name: default sh is bash
      file:
        src=/bin/bash
        dest=/bin/sh
        state=link

    - name: check packer is installed
      stat: path=/usr/local/bin/packer
      register: packer_bin_check

    - name: setting fact
      set_fact:
        packer_installed="{{ packer_bin_check.stat.exists }}"

    - name: get jenkins plugin list
      shell: "/usr/local/bin/packer --version"
      register: packer_version

    - name: setting fact
      set_fact:
        need_to_install_packer="{{(not packer_installed) or (not packer_version.stdout == os_image_factory.packer.version)}}"

    - name: packer dest directory ready
      when: need_to_install_packer
      file:
        path=/usr/local/bin
        state=directory
        owner=root
        group=staff
        mode=0755

    - name: packer download
      when: need_to_install_packer
      get_url:
        url="{{ os_image_factory.packer.zip_url }}"
        dest=/tmp/packer.zip
        force=no

    - name: unzip packer
      when: need_to_install_packer
      unarchive:
        src=/tmp/packer.zip
        dest=/usr/local/bin
        copy=no
        owner=root
        group=staff
        mode=0755

    - name: pip packages installed
      pip:
        name="{{ item }}"
        state=latest
      with_items:
        - python-glanceclient
        - python-novaclient
        - python-neutronclient
        - python-heatclient
        - python-openstackclient
        - python-cinderclient

    - name: download jenkins CLI jar file
      get_url:
        url="{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
        dest=/root/jenkins-cli.jar
        force=no
      register: cli_download
      until: cli_download|success
      retries: 6
      delay: 5

    - name: get jenkins plugin list
      shell: "java -jar /root/jenkins-cli.jar -s {{ jenkins_url }} list-plugins | grep -e ')$' | awk '{ print $1 }' | tr \"\n\" \" \""
      register: jenkins_plugins

    - name: update jenkins
      when: jenkins_plugins.stdout
      shell: "java -jar /root/jenkins-cli.jar -s {{ jenkins_url }} install-plugin {{ jenkins_plugins.stdout }}"

    - name: install jenkins git plugin
      shell: "java -jar /root/jenkins-cli.jar -s {{ jenkins_url }} install-plugin git-client git"

    - name: restart jenkins
      shell: "java -jar /root/jenkins-cli.jar -s {{ jenkins_url }} safe-restart"
